### ISSUE TITLE
Database login fixes

### ISSUE THREAD

**Issue by ariane-codes** [ariane-codes/sde-constella#7]
Two improvements / bug fixes to make:

1. The `login` function of the `Database` class returns a success message if the password matches the one persisted in the db. We want to also want to return all the user information along with it, including an `employee_id` and the employee name to be used later on.
2. In the criteria, we said that user would log in with email and password, but right now it's set up with a username. Change it to email.

Great catches @phil-griffith ! Thank you.

**Comment by ariane-codes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Database fixes](https://trello.com/c/yb238PkC/40-database-fixes)

**Comment by ariane-codes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Reports] Testing: 3 Bug reports](https://trello.com/c/LvGX6Unf/37-reports-testing-3-bug-reports)

**Comment by ariane-codes** [comment]
By the way @phil-griffith , don't forget to update the tests to reflect your changes!

**Comment by phil-griffith** [comment]
Done login now takes email and returns employee information in the dictionary
